### ISSUE TITLE
[FE] 댓글/답변 레이아웃 구현

### ISSUE THREAD

**Issue by YebinYun** [codestates-seb/seb45_main_027#82]
## Description
설명을 작성하세요.

## Todo
- [ ] todo
- [ ] todo

## ETC
기타사항

**Comment by YebinYun** [comment]
## ⚒️ 댓글 / 답변

- [ ] 댓글 작성 입력창
- [ ] 댓글 작성자 정보
- [ ] 작성날짜, 좋아요 (on/off 적용), 답글작성 버튼 (on/off 적용)

- [ ] 답글 작성입력창
- [ ] 답글 작성자 정보
- [ ] 작성날

## 🎀 이미지 첨부

![Image](https://github.com/codestates-seb/seb45_main_027/assets/122279587/df4ad300-a291-4cbf-92c7-0b10242e110a)
